sudo: false
language: node_js
node_js:
- '0.12'
script: "npm run-script ci"
env:
  - DEBUG=* MONGODB_VERSION=2.4.x MONGODB_TOPOLOGY=cluster
  - DEBUG=* MONGODB_VERSION=2.4.x MONGODB_TOPOLOGY=standalone
  - DEBUG=* MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=cluster
  - DEBUG=* MONGODB_VERSION=2.6.x MONGODB_TOPOLOGY=standalone
  - DEBUG=* MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=cluster
  - DEBUG=* MONGODB_VERSION=3.0.x MONGODB_TOPOLOGY=standalone
  - DEBUG=* MONGODB_VERSION=3.1.x MONGODB_TOPOLOGY=standalone
